-- Durable Telegram update claim lifecycle. Existing rows represent completed updates.
SET @db:=DATABASE();
SET @q:=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND COLUMN_NAME='status')=0,"ALTER TABLE processed_updates ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'completed' AFTER processed_at",'SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q:=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND COLUMN_NAME='claim_token')=0,'ALTER TABLE processed_updates ADD COLUMN claim_token CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER status','SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q:=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND COLUMN_NAME='started_at')=0,'ALTER TABLE processed_updates ADD COLUMN started_at INT UNSIGNED NULL AFTER claim_token','SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q:=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND COLUMN_NAME='completed_at')=0,'ALTER TABLE processed_updates ADD COLUMN completed_at INT UNSIGNED NULL AFTER started_at','SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q:=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND COLUMN_NAME='failure_code')=0,'ALTER TABLE processed_updates ADD COLUMN failure_code VARCHAR(64) NULL AFTER completed_at','SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q:=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND COLUMN_NAME='attempts')=0,'ALTER TABLE processed_updates ADD COLUMN attempts INT UNSIGNED NOT NULL DEFAULT 1 AFTER failure_code','SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
UPDATE processed_updates SET status='completed',completed_at=COALESCE(completed_at,processed_at),attempts=GREATEST(attempts,1) WHERE status IS NULL OR status='' OR status NOT IN ('processing','completed','failed');
SET @q:=IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='processed_updates' AND INDEX_NAME='idx_processed_updates_lifecycle')=0,'ALTER TABLE processed_updates ADD INDEX idx_processed_updates_lifecycle(status,processed_at)','SELECT 1');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
