<?php
declare(strict_types=1);require_once __DIR__.'/../lib/CronGuard.php';rx_cron_authorize();require_once __DIR__.'/../config.php';require_once __DIR__.'/../botapi.php';rx_cron_telemetry_start($pdo,'reseller_messages');
$lock=fopen(sys_get_temp_dir().'/redfox_reseller_messages.lock','c');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))exit;$claim=bin2hex(random_bytes(16));$now=time();
try{$pdo->prepare("UPDATE reseller_message_queue SET status='needs_reconcile',claim_token=NULL,claimed_at=NULL,last_error='worker interrupted after claim' WHERE status='processing' AND claimed_at IS NOT NULL AND claimed_at<?")->execute([$now-900]);$pdo->beginTransaction();$q=$pdo->prepare("SELECT q.id FROM reseller_message_queue q JOIN reseller_broadcasts b ON b.broadcast_id=q.broadcast_id WHERE q.status IN ('queued','retry') AND q.next_attempt_at<=? AND b.status IN ('queued','processing') ORDER BY q.id LIMIT 50 FOR UPDATE");$q->execute([$now]);$ids=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));if($ids){$ph=implode(',',array_fill(0,count($ids),'?'));$u=$pdo->prepare("UPDATE reseller_message_queue SET status='processing',claim_token=?,claimed_at=? WHERE id IN ($ph) AND status IN ('queued','retry')");$u->execute(array_merge([$claim,$now],$ids));}$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('[reseller messages claim] '.redfox_exception_fingerprint($e));exit;}
if(!$ids)exit;$q=$pdo->prepare("SELECT q.*,b.message,b.status broadcast_status FROM reseller_message_queue q JOIN reseller_broadcasts b ON b.broadcast_id=q.broadcast_id WHERE q.claim_token=? ORDER BY q.id");$q->execute([$claim]);$items=$q->fetchAll(PDO::FETCH_ASSOC);
foreach($items as$item){$ok=false;$error='';try{$bs=$pdo->prepare('SELECT status FROM reseller_broadcasts WHERE broadcast_id=?');$bs->execute([$item['broadcast_id']]);if((string)$bs->fetchColumn()==='cancelled')throw new RuntimeException('cancelled');$token=null;if(!empty($item['bot_owner_id'])){$t=$pdo->prepare("SELECT bot_token FROM botsaz WHERE id_user=? AND (bot_status IS NULL OR bot_status='active') LIMIT 1");$t->execute([$item['bot_owner_id']]);$token=(string)$t->fetchColumn();if($token==='')throw new RuntimeException('reseller bot unavailable');}$resp=sendmessage((string)$item['recipient_user_id'],(string)$item['message'],null,null,$token);$ok=is_array($resp)&&!empty($resp['ok']);if(!$ok)$error='telegram_send_failed';}catch(Throwable$e){$error=mb_substr(redfox_exception_fingerprint($e),0,900);}
 $attempt=(int)$item['attempts']+1;if($ok){$pdo->prepare("UPDATE reseller_message_queue SET status='sent',attempts=?,claim_token=NULL,claimed_at=NULL,last_error=NULL,sent_at=? WHERE id=? AND claim_token=?")->execute([$attempt,time(),$item['id'],$claim]);}elseif($attempt>=5||$error==='cancelled'){$st=$error==='cancelled'?'cancelled':'failed';$pdo->prepare("UPDATE reseller_message_queue SET status=?,attempts=?,claim_token=NULL,claimed_at=NULL,last_error=? WHERE id=? AND claim_token=?")->execute([$st,$attempt,$error,$item['id'],$claim]);}else{$delay=min(3600,30*(2**($attempt-1)));$pdo->prepare("UPDATE reseller_message_queue SET status='retry',attempts=?,claim_token=NULL,claimed_at=NULL,last_error=?,next_attempt_at=? WHERE id=? AND claim_token=?")->execute([$attempt,$error,time()+$delay,$item['id'],$claim]);}usleep(50000);
}
$broadcasts=array_unique(array_column($items,'broadcast_id'));foreach($broadcasts as$bid){$s=$pdo->prepare("SELECT SUM(status='sent') sent,SUM(status='failed') failed,SUM(status IN ('queued','retry','processing','needs_reconcile')) pending FROM reseller_message_queue WHERE broadcast_id=?");$s->execute([$bid]);$c=$s->fetch(PDO::FETCH_ASSOC);$status=(int)$c['pending']>0?'processing':'completed';$pdo->prepare('UPDATE reseller_broadcasts SET sent_count=?,failed_count=?,status=?,completed_at=? WHERE broadcast_id=? AND status<>\'cancelled\'')->execute([(int)$c['sent'],(int)$c['failed'],$status,$status==='completed'?time():null,$bid]);}
