<?php
declare(strict_types=1);
function rx_content_token(string$s):string{return rtrim(strtr(base64_encode($s),'+/','-_'),'=');}
function rx_content_untoken(string$s):?string{$x=strtr($s,'-_','+/');$x.=str_repeat('=',(4-strlen($x)%4)%4);$v=base64_decode($x,true);return is_string($v)?$v:null;}
function rx_content_categories(PDO$pdo,string$section):array{$out=[];try{$q=$pdo->prepare('SELECT name FROM content_categories WHERE section=? AND enabled=1 ORDER BY sort_order,id');$q->execute([$section]);$out=$q->fetchAll(PDO::FETCH_COLUMN);$q->closeCursor();}catch(Throwable$e){}if(!$out){try{$col=$section==='help'?'category':'platform';$table=$section==='help'?'help':'app';$out=$pdo->query("SELECT DISTINCT `$col` FROM `$table` WHERE `$col` IS NOT NULL AND TRIM(`$col` )<>'' ORDER BY `$col`")->fetchAll(PDO::FETCH_COLUMN);}catch(Throwable$e){}}$seen=[];$clean=[];foreach($out as$n){$k=mb_strtolower(trim((string)$n),'UTF-8');if($k!==''&&!isset($seen[$k])){$seen[$k]=1;$clean[]=trim((string)$n);}}return$clean;}
function rx_content_category_keyboard(PDO$pdo,string$section,string$prefix,string$back='backuser'):string{$kb=['inline_keyboard'=>[]];foreach(rx_content_categories($pdo,$section)as$name)$kb['inline_keyboard'][]=[['text'=>($section==='help'?'📚 ':'💻 ').$name,'callback_data'=>$prefix.rx_content_token($name)]];$kb['inline_keyboard'][]=[['text'=>'🔙 بازگشت','callback_data'=>$back]];return json_encode($kb,JSON_UNESCAPED_UNICODE);}
function rx_content_software_keyboard(PDO$pdo,string$category,string$backPrefix):string{$q=$pdo->prepare('SELECT name,link FROM app WHERE enabled=1 AND platform=? ORDER BY name');try{$q->execute([$category]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable$e){$q=$pdo->prepare('SELECT name,link FROM app WHERE platform=? ORDER BY name');$q->execute([$category]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}$kb=['inline_keyboard'=>[]];foreach($rows as$r)$kb['inline_keyboard'][]=[['text'=>$r['name'],'url'=>$r['link']]];$kb['inline_keyboard'][]=[['text'=>'🔙 سیستم‌عامل‌ها','callback_data'=>$backPrefix]];return json_encode($kb,JSON_UNESCAPED_UNICODE);}
function rx_content_help_items(PDO$pdo,string$category,string$backPrefix):string{$q=$pdo->prepare('SELECT id,name_os FROM help WHERE category=? ORDER BY id');$q->execute([$category]);$kb=['inline_keyboard'=>[]];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r)$kb['inline_keyboard'][]=[['text'=>$r['name_os'],'callback_data'=>'rxhelpitem_'.$r['id']]];$kb['inline_keyboard'][]=[['text'=>'🔙 دسته‌های آموزش','callback_data'=>$backPrefix]];return json_encode($kb,JSON_UNESCAPED_UNICODE);}
function rx_content_help_row(PDO$pdo,int$id):?array{$q=$pdo->prepare('SELECT * FROM help WHERE id=? LIMIT 1');$q->execute([$id]);$r=$q->fetch(PDO::FETCH_ASSOC);return$r?:null;}
