<?php
declare(strict_types=1);
final class RedFoxCertification {
 private PDO$pdo;private string$root;private array$checks=[];
 public function __construct(PDO$pdo,string$root){$this->pdo=$pdo;$this->root=$root;}
 private function add(string$name,string$status,string$message='',array$meta=[]):void{$this->checks[]=['name'=>$name,'status'=>$status,'message'=>$message,'meta'=>rx_redact($meta)];}
 public function run():array{$this->environment();$this->database();$this->secrets();$this->panels();$this->gateways();$this->operations();$score=0;$fail=0;foreach($this->checks as$c){if($c['status']==='pass')$score+=2;elseif($c['status']==='warn')$score+=1;else$fail++;}$max=max(1,count($this->checks)*2);return['status'=>$fail?'failed':($score<$max?'warning':'passed'),'score'=>(int)round($score/$max*100),'checks'=>$this->checks,'created_at'=>time()];}
 private function environment():void{$this->add('php_8_4',version_compare(PHP_VERSION,'8.4','>=')?'pass':'fail',PHP_VERSION);foreach(['pdo_mysql','mysqli','curl','json','mbstring','openssl','zip']as$e)$this->add('ext_'.$e,extension_loaded($e)?'pass':'fail');$this->add('storage_protected',is_file($this->root.'/storage/.htaccess')?'pass':'fail');$this->add('logs_protected',is_file($this->root.'/logs/.htaccess')?'pass':'fail');$origin=function_exists('redfox_configured_base_url')?redfox_configured_base_url():'';if($origin!==''){foreach(['/config.php','/table.php','/storage/secure.env.php','/logs/application.jsonl']as$path){$ch=curl_init($origin.$path);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_NOBODY=>true,CURLOPT_CONNECTTIMEOUT=>2,CURLOPT_TIMEOUT=>4,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);$policy=redfox_apply_curl_url_policy($ch,$origin.$path,false,false);if(empty($policy['ok'])){curl_close($ch);$this->add('web_deny_'.str_replace(['/','.'],['_','_'],trim($path,'/')),'warn','endpoint_blocked');continue;}curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$this->add('web_deny_'.str_replace(['/','.'],['_','_'],trim($path,'/')),in_array($code,[403,404],true)?'pass':($code===0?'warn':'fail'),'HTTP '.$code);}}try{$r=RedFoxSecureUpdater::verifyRelease($this->root);$this->add('release_integrity',!empty($r['ok'])?'pass':(!empty($r['unsigned'])?'warn':'fail'),implode(';',$r['errors']??[]));}catch(Throwable$e){$this->add('release_integrity','fail',redfox_exception_fingerprint($e));}}
 private function database():void{try{$m=$this->pdo->query("SELECT COUNT(*) FROM schema_migrations WHERE version='013_update_progress_ui.sql'")->fetchColumn();$this->add('migration_013',(int)$m===1?'pass':'fail');$dup=(int)$this->pdo->query("SELECT COUNT(*) FROM (SELECT id_order FROM Payment_report WHERE id_order<>'' GROUP BY id_order HAVING COUNT(*)>1)d")->fetchColumn();$this->add('payment_order_duplicates',$dup===0?'pass':'fail',$dup.' duplicate groups');$orph=(int)$this->pdo->query('SELECT COUNT(*) FROM invoice i LEFT JOIN user u ON u.id=i.id_user WHERE u.id IS NULL')->fetchColumn();$this->add('orphan_invoices',$orph===0?'pass':'fail',$orph.' orphan rows');}catch(Throwable$e){$this->add('database_contract','fail',redfox_exception_fingerprint($e));}}
 private function secrets():void{foreach(['REDFOX_MASTER_KEY','REDFOX_BACKUP_KEY','REDFOX_CRON_SECRET','REDFOX_DIAG_SECRET','REDFOX_HEALTH_TOKEN']as$k)$this->add('secret_'.$k,(string)rx_env($k)!==''?'pass':'fail');try{$ids=RedFoxSecureUpdater::trustedKeyIds();$this->add('update_keyring',$ids?'pass':'fail',implode(',',$ids));}catch(Throwable$e){$this->add('update_keyring','warn','updater disabled until a trusted key is configured');}}
 private function panels():void{try{$rows=$this->pdo->query("SELECT id,name_panel,url_panel,type,status,password_panel,api_key FROM marzban_panel ORDER BY id LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);$this->add('panels_configured',$rows?'pass':'warn',count($rows).' panels');foreach($rows as$p){$name='panel_'.($p['name_panel']?:$p['id']);$url=(string)$p['url_panel'];if(!filter_var($url,FILTER_VALIDATE_URL)){$this->add($name,'fail','invalid URL');continue;}$https=str_starts_with(strtolower($url),'https://');$encrypted=(empty($p['password_panel'])||rx_secret_is_encrypted((string)$p['password_panel']))&&(empty($p['api_key'])||rx_secret_is_encrypted((string)$p['api_key']));$net=$this->probe($url,true);$status=$net['ok']&&$https&&$encrypted?'pass':($net['ok']?'warn':'fail');$this->add($name,$status,'type='.$p['type'].' https='.($https?'yes':'no').' encrypted='.($encrypted?'yes':'no').' '.$net['message']);}}catch(Throwable$e){$this->add('panels','fail',redfox_exception_fingerprint($e));}}
 private function gateways():void{$defs=[['zarinpalstatus','onzarinpal','merchant_zarinpal','https://api.zarinpal.com'],['statusaqayepardakht','onaqayepardakht','merchant_id_aqayepardakht','https://panel.aqayepardakht.ir'],['nowpaymentstatus','onnowpayment','api_nowpayment','https://api.nowpayments.io'],['digistatus','ondigi','api_plisio','https://api.plisio.net'],['statustarnado','onternado','apiternado','https://bot.tronado.cloud'],['statusSwapWallet','onSwapinoBot','marchent_tronseller','https://api.trongrid.io'],['statusiranpay3','oniranpay3','marchent_floypay','https://tetra98.com']];try{$q=$this->pdo->query('SELECT NamePay,ValuePay FROM PaySetting');$map=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r)$map[(string)$r['NamePay']]=(string)$r['ValuePay'];foreach($defs as[$sk,$on,$ck,$url]){$enabled=($map[$sk]??'')===$on;$credential=trim($map[$ck]??'');$net=$this->probe($url);$status=$enabled?($credential!==''&&$credential!=='0'&&$net['ok']?'pass':'fail'):'warn';$this->add('gateway_'.$sk,$status,$enabled?'enabled; '.$net['message']:'disabled');}$card=(string)($map['Cartstatus']??'');$this->add('gateway_card',$card==='oncard'?'pass':'warn',$card);}catch(Throwable$e){$this->add('gateways','fail',redfox_exception_fingerprint($e));}}
 private function operations():void{try{$recon=(int)$this->pdo->query("SELECT (SELECT COUNT(*) FROM payment_effects WHERE status='needs_reconcile')+(SELECT COUNT(*) FROM reseller_service_operations WHERE status='needs_reconcile')+(SELECT COUNT(*) FROM reseller_message_queue WHERE status='needs_reconcile')")->fetchColumn();$this->add('reconciliation_queue',$recon===0?'pass':'warn',$recon.' pending');$last=(int)$this->pdo->query("SELECT COALESCE(MAX(started_at),0) FROM cron_job_runs WHERE job_name='orchestrator' AND status='completed'")->fetchColumn();$age=$last?time()-$last:PHP_INT_MAX;$this->add('cron_orchestrator',$age<300?'pass':'fail',$last?($age.' seconds ago'):'never');}catch(Throwable$e){$this->add('operations','fail',redfox_exception_fingerprint($e));}}
 private function probe(string$url,bool$panel=false):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_NOBODY=>true,CURLOPT_CONNECTTIMEOUT=>2,CURLOPT_TIMEOUT=>4,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);$policy=$panel?redfox_apply_panel_curl_url_policy($ch,$url):redfox_apply_curl_url_policy($ch,$url,false,false);if(empty($policy['ok'])){curl_close($ch);return['ok'=>false,'message'=>'endpoint_blocked'];}curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$errno=(int)curl_errno($ch);curl_close($ch);return['ok'=>$errno===0&&$code>0&&$code<500,'message'=>$errno!==0?'transport_errno_'.$errno:'HTTP '.$code];}
}
