<?php
declare(strict_types=1);require_once __DIR__.'/PdfTextExtractor.php';
final class RedFoxKnowledgeBase{
 const MAX_TEXT_CHARS=250000;const MAX_UPLOAD_BYTES=10485760;
 public static function add(PDO$pdo,string$title,string$body,string$source='text'):int{$title=trim($title);$body=self::normalize($body);if($body==='')throw new RuntimeException('متن نمی‌تواند خالی باشد.');if($title==='')$title='سند دانش '.date('Y/m/d H:i');if(mb_strlen($title,'UTF-8')>1000)throw new RuntimeException('عنوان بیش از حد طولانی است.');if(mb_strlen($body,'UTF-8')>self::MAX_TEXT_CHARS)throw new RuntimeException('متن حداکثر ۲۵۰ هزار کاراکتر باشد.');$s=$pdo->prepare('INSERT INTO ai_knowledge(question,answer,source,enabled,created_at,updated_at) VALUES(?,?,?,1,?,?)');$now=date('Y-m-d H:i:s');$s->execute([$title,$body,$source,$now,$now]);return(int)$pdo->lastInsertId();}
 public static function update(PDO$pdo,int$id,string$title,string$body):void{if($id<=0)throw new RuntimeException('شناسه دانش نامعتبر است.');$title=trim($title);$body=self::normalize($body);if($title===''||$body==='')throw new RuntimeException('عنوان و متن هر دو لازم هستند.');if(mb_strlen($title,'UTF-8')>1000||mb_strlen($body,'UTF-8')>self::MAX_TEXT_CHARS)throw new RuntimeException('طول عنوان یا متن بیش از حد مجاز است.');$s=$pdo->prepare('UPDATE ai_knowledge SET question=?,answer=?,updated_at=? WHERE id=?');$s->execute([$title,$body,date('Y-m-d H:i:s'),$id]);if($s->rowCount()===0){$c=$pdo->prepare('SELECT COUNT(*) FROM ai_knowledge WHERE id=?');$c->execute([$id]);$exists=(int)$c->fetchColumn()>0;$c->closeCursor();if(!$exists)throw new RuntimeException('رکورد دانش پیدا نشد.');}}
 public static function fromUpload(PDO$pdo,array$file):array{$err=(int)($file['error']??UPLOAD_ERR_NO_FILE);if($err!==UPLOAD_ERR_OK)throw new RuntimeException('آپلود فایل ناموفق بود (کد '.$err.').');$size=(int)($file['size']??0);$tmp=(string)($file['tmp_name']??'');$name=(string)($file['name']??'document');if($size<1||$size>self::MAX_UPLOAD_BYTES||!is_uploaded_file($tmp))throw new RuntimeException('فایل نامعتبر است یا بیش از ۱۰ مگابایت حجم دارد.');$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$allowed=['txt','md','csv','pdf'];if(!in_array($ext,$allowed,true))throw new RuntimeException('فقط فایل‌های TXT، MD، CSV و PDF مجاز هستند.');$mime='';if(function_exists('finfo_open')){$f=finfo_open(FILEINFO_MIME_TYPE);if($f){$mime=(string)finfo_file($f,$tmp);finfo_close($f);}}if($ext==='pdf'){$head=(string)file_get_contents($tmp,false,null,0,5);if($head!=='%PDF-')throw new RuntimeException('فایل انتخاب‌شده PDF معتبر نیست.');$content=RedFoxPdfTextExtractor::extract($tmp);$source='pdf';}else{if($mime!==''&&!str_starts_with($mime,'text/')&&!in_array($mime,['application/csv','application/octet-stream'],true))throw new RuntimeException('نوع واقعی فایل متنی نیست.');$content=(string)file_get_contents($tmp);$content=self::toUtf8($content);$source='file';}$id=self::add($pdo,mb_strimwidth($name,0,500,'','UTF-8'),$content,$source);return['id'=>$id,'source'=>$source,'chars'=>mb_strlen($content,'UTF-8')];}
 private static function normalize(string$s):string{$s=self::toUtf8($s);$s=str_replace("\0",'',$s);$s=preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u',' ',$s);$s=preg_replace('/[ \t]+\n/u',"\n",$s);$s=preg_replace('/\n{4,}/u',"\n\n\n",$s);return trim($s);}
 private static function toUtf8(string$s):string{if(mb_check_encoding($s,'UTF-8'))return$s;$d=mb_detect_encoding($s,['UTF-16','Windows-1256','ISO-8859-1','ASCII'],true);if($d!==false)return(string)@mb_convert_encoding($s,'UTF-8',$d);return(string)@iconv('UTF-8','UTF-8//IGNORE',$s);}
}
