<?php
declare(strict_types=1);
function rx_message_template_definitions():array{return[
 'report_reseller_purchase'=>['title'=>'گزارش خرید موفق در ربات نماینده','group'=>'گزارش‌های خرید نماینده','vars'=>['first_purchase','user_id','agent_id','user_username','reseller_bot','config_username','customer_name','panel_name','service_days','volume_gb','user_balance_before','user_balance_after','agent_balance_before','agent_balance_after','tracking_code','product_price','purchase_time'],'default'=>"📣 خرید موفق در ربات نماینده ثبت شد.\n\n{first_purchase}\n👤 کاربر: <code>{user_id}</code> — @{user_username}\n🧑‍💼 نماینده: <code>{agent_id}</code> — ربات @{reseller_bot}\n🔐 نام کانفیگ: <code>{config_username}</code>\n🖥 پنل: {panel_name}\n⏳ مدت: {service_days} روز | 💾 حجم: {volume_gb} GB\n💰 موجودی کاربر: {user_balance_before} ← {user_balance_after} تومان\n💼 موجودی نماینده: {agent_balance_before} ← {agent_balance_after} تومان\n💳 قیمت محصول: {product_price} تومان\n🧾 پیگیری: <code>{tracking_code}</code>\n🕒 زمان: {purchase_time}"],
 'report_reseller_extend'=>['title'=>'گزارش تمدید در ربات نماینده','group'=>'گزارش‌های خرید نماینده','vars'=>['user_id','agent_id','reseller_bot','user_username','config_username','customer_name','panel_name','product_name','volume_gb','service_days','product_price','user_balance_before','user_balance_after','agent_balance_before','agent_balance_after','purchase_time'],'default'=>"♻️ تمدید سرویس در ربات نماینده ثبت شد.\n\n👤 کاربر: <code>{user_id}</code> — @{user_username}\n🧑‍💼 نماینده: <code>{agent_id}</code> — ربات @{reseller_bot}\n🔐 سرویس: <code>{config_username}</code>\n🛍 محصول: {product_name}\n🖥 پنل: {panel_name}\n⏳ مدت: {service_days} روز | 💾 حجم: {volume_gb} GB\n💰 موجودی کاربر: {user_balance_before} ← {user_balance_after} تومان\n💼 موجودی نماینده: {agent_balance_before} ← {agent_balance_after} تومان\n💳 مبلغ تمدید: {product_price} تومان\n🕒 زمان: {purchase_time}"],
 'report_reseller_test'=>['title'=>'گزارش ساخت اکانت تست نماینده','group'=>'گزارش‌های خرید نماینده','vars'=>['user_id','agent_id','reseller_bot','user_username','config_username','customer_name','panel_name','test_hours','test_volume','tracking_code','purchase_time'],'default'=>"🧪 اکانت تست در ربات نماینده ساخته شد.\n\n👤 کاربر: <code>{user_id}</code> — @{user_username}\n🧑‍💼 نماینده: <code>{agent_id}</code> — ربات @{reseller_bot}\n🔐 کانفیگ: <code>{config_username}</code>\n🖥 پنل: {panel_name}\n⏳ زمان تست: {test_hours} ساعت | 💾 حجم: {test_volume} MB\n🧾 پیگیری: <code>{tracking_code}</code>\n🕒 زمان: {purchase_time}"],
 'alert_reseller_no_credit_customer'=>['title'=>'پیام کمبود اعتبار نماینده به مشتری','group'=>'هشدارهای اعتبار نماینده','vars'=>['agent_id','agent_balance','required_amount'],'default'=>"❌ اعتبار فروشنده برای ساخت این سرویس کافی نیست.\nلطفاً با فروشنده تماس بگیرید تا حساب نمایندگی را شارژ کند."],
 'alert_reseller_no_credit_admin'=>['title'=>'هشدار اتمام اعتبار به نماینده/ادمین','group'=>'هشدارهای اعتبار نماینده','vars'=>['agent_id','agent_balance','required_amount'],'default'=>"⚠️ اعتبار نماینده برای فروش کافی نیست.\nنماینده: <code>{agent_id}</code>\nموجودی فعلی: {agent_balance} تومان\nمبلغ لازم: {required_amount} تومان\nلطفاً حساب نمایندگی شارژ شود."],
 'alert_reseller_low_balance'=>['title'=>'هشدار رسیدن موجودی نماینده به حد کم','group'=>'هشدارهای اعتبار نماینده','vars'=>['agent_id','agent_balance','threshold'],'default'=>"⚠️ هشدار کاهش اعتبار نمایندگی\nنماینده: <code>{agent_id}</code>\nموجودی فعلی: {agent_balance} تومان\nحد هشدار: {threshold} تومان\nبرای جلوگیری از توقف فروش، حساب را شارژ کنید."],
 ];}
function rx_message_template(PDO$pdo,string$key,array$vars=[],?string$fallback=null):string{static$defs=null;$defs??=rx_message_template_definitions();$default=$fallback??($defs[$key]['default']??'');try{$q=$pdo->prepare('SELECT text FROM textbot WHERE id_text=? LIMIT 1');$q->execute([$key]);$v=$q->fetchColumn();$q->closeCursor();$tpl=($v!==false&&trim((string)$v)!=='')?(string)$v:$default;}catch(Throwable$e){$tpl=$default;}$replace=[];foreach($vars as$k=>$v)$replace['{'.$k.'}']=htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');return strtr($tpl,$replace);}
