<?php
declare(strict_types=1);
final class RedFoxPdfTextExtractor{
 public static function extract(string$file):string{if(!is_file($file)||filesize($file)<8||filesize($file)>10485760)throw new RuntimeException('اندازه PDF نامعتبر است.');$head=(string)file_get_contents($file,false,null,0,8);if(!str_starts_with($head,'%PDF-'))throw new RuntimeException('ساختار فایل PDF معتبر نیست.');if(class_exists('Smalot\\PdfParser\\Parser')){try{$p=new Smalot\PdfParser\Parser();$t=trim($p->parseFile($file)->getText());if($t!=='')return self::clean($t);}catch(Throwable$e){}}
  $bin='';if(function_exists('shell_exec')&&is_callable('shell_exec'))$bin=trim((string)@shell_exec('command -v pdftotext 2>/dev/null'));if($bin!==''&&is_executable($bin)){ $tmp=tempnam(sys_get_temp_dir(),'rxpdf-');$cmd=escapeshellarg($bin).' -layout -enc UTF-8 '.escapeshellarg($file).' '.escapeshellarg($tmp).' 2>/dev/null';@shell_exec($cmd);$t=is_file($tmp)?trim((string)file_get_contents($tmp)):'';@unlink($tmp);if($t!=='')return self::clean($t);}
  $raw=(string)file_get_contents($file);$chunks=[];if(preg_match_all('/stream\r?\n(.*?)\r?\nendstream/s',$raw,$m,PREG_OFFSET_CAPTURE)){foreach($m[1]as$item){$data=$item[0];$pos=$item[1];$dict=substr($raw,max(0,$pos-600),min(600,$pos));if(str_contains($dict,'/FlateDecode')){$u=@gzuncompress($data);if($u===false)$u=@gzinflate($data);if(is_string($u))$data=$u;}self::collectStrings($data,$chunks);if(count($chunks)>10000)break;}}$text=self::clean(implode("\n",$chunks));if(mb_strlen($text,'UTF-8')<20)throw new RuntimeException('متن قابل استخراج از PDF پیدا نشد؛ احتمالاً فایل اسکن‌شده/تصویری است. PDF متنی یا فایل TXT ارسال کنید.');return$text;}
 private static function collectStrings(string$data,array&$out):void{if(preg_match_all('/\((?:\\.|[^\\)])*\)\s*Tj|\[(.*?)\]\s*TJ|<([0-9A-Fa-f]+)>\s*Tj/s',$data,$ops,PREG_SET_ORDER)){foreach($ops as$op){if(str_starts_with($op[0],'(')){$end=strrpos($op[0],')');$out[]=self::decodeLiteral(substr($op[0],1,$end-1));}elseif(!empty($op[1])){if(preg_match_all('/\((?:\\.|[^\\)])*\)|<([0-9A-Fa-f]+)>/s',$op[1],$parts))foreach($parts[0]as$p)$out[]=str_starts_with($p,'(')?self::decodeLiteral(substr($p,1,-1)):self::decodeHex(trim($p,'<>'));}elseif(!empty($op[2]))$out[]=self::decodeHex($op[2]);}}}
 private static function decodeLiteral(string$s):string{$s=preg_replace_callback('/\\\\([0-7]{1,3})/',fn($m)=>chr(octdec($m[1])),$s);$s=strtr($s,['\\n'=>"\n",'\\r'=>"\r",'\\t'=>"\t",'\\('=>'(','\\)'=>')','\\\\'=>'\\']);return self::decodeBytes($s);}
 private static function decodeHex(string$h):string{if(strlen($h)%2)$h.='0';$b=@hex2bin($h);return is_string($b)?self::decodeBytes($b):'';}
 private static function decodeBytes(string$s):string{if(str_starts_with($s,"\xFE\xFF"))return (string)@mb_convert_encoding(substr($s,2),'UTF-8','UTF-16BE');if(str_starts_with($s,"\xFF\xFE"))return (string)@mb_convert_encoding(substr($s,2),'UTF-8','UTF-16LE');if(mb_check_encoding($s,'UTF-8'))return$s;$d=mb_detect_encoding($s,['Windows-1256','ISO-8859-1','ASCII'],true);return$d?(string)@mb_convert_encoding($s,'UTF-8',$d):'';}
 private static function clean(string$s):string{$s=str_replace("\0",'',$s);$s=preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u',' ',$s);$s=preg_replace('/[ \t]+/u',' ',$s);$s=preg_replace('/\n{3,}/u',"\n\n",$s);return trim($s);}
}
