<?php
declare(strict_types=1);
final class RedFoxResellerSettlements {
 private PDO$pdo;private array$ctx;public function __construct(PDO$pdo,array$ctx){$this->pdo=$pdo;$this->ctx=$ctx;}
 public function settings():array{$r=$this->pdo->query('SELECT * FROM reseller_settlement_settings WHERE id=1')->fetch(PDO::FETCH_ASSOC);return$r?:['enabled'=>0,'min_amount'=>100000,'fee_percent'=>0,'hold_hours'=>24];}
 public function saveAccount(string$iban,string$holder):void{if(rx_secret_master_key()===null)throw new RuntimeException('کلید رمزنگاری اصلی تنظیم نشده است.');$iban=strtoupper(preg_replace('/\s+/','',$iban));$holder=mb_substr(trim($holder),0,191);if(!$this->validIban($iban)||$holder==='')throw new RuntimeException('شماره شبا یا نام صاحب حساب نامعتبر است.');$this->pdo->beginTransaction();try{$this->pdo->prepare('UPDATE reseller_payout_accounts SET is_active=0 WHERE reseller_id=?')->execute([$this->ctx['id']]);$this->pdo->prepare("INSERT INTO reseller_payout_accounts(reseller_id,holder_name,iban_cipher,iban_last4,status,is_active,created_at) VALUES(?,?,?,?, 'pending',1,?)")->execute([$this->ctx['id'],$holder,rx_secret_encrypt($iban),substr($iban,-4),time()]);$this->pdo->commit();rxp_audit($this->pdo,$this->ctx,'settlement.account',$this->ctx['id']);}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 public function request(int$amount,string$idem):array{$s=$this->settings();if(empty($s['enabled']))throw new RuntimeException('درخواست تسویه غیرفعال است.');if($amount<(int)$s['min_amount'])throw new RuntimeException('مبلغ کمتر از حداقل تسویه است.');if(!preg_match('/^[a-f0-9]{32,64}$/',$idem))throw new RuntimeException('کلید درخواست نامعتبر است.');$q=$this->pdo->prepare("SELECT * FROM reseller_payout_accounts WHERE reseller_id=? AND is_active=1 AND status='verified' LIMIT 1");$q->execute([$this->ctx['id']]);$acc=$q->fetch(PDO::FETCH_ASSOC);if(!$acc)throw new RuntimeException('ابتدا شبای تأییدشده لازم است.');$q=$this->pdo->prepare("SELECT (SELECT COUNT(*) FROM reseller_service_operations WHERE owner_reseller_id=? AND status='needs_reconcile')+(SELECT COUNT(*) FROM payment_effects pe JOIN Payment_report p ON p.id_order=pe.order_id WHERE p.id_user=? AND pe.status='needs_reconcile')");$q->execute([$this->ctx['id'],$this->ctx['id']]);if((int)$q->fetchColumn()>0)throw new RuntimeException('ابتدا موارد نیازمند تطبیق را رفع کنید.');$fee=(int)round($amount*(float)$s['fee_percent']/100);$net=$amount-$fee;if($net<=0)throw new RuntimeException('مبلغ خالص نامعتبر است.');$id=bin2hex(random_bytes(16));$this->pdo->beginTransaction();try{$dup=$this->pdo->prepare('SELECT * FROM reseller_settlements WHERE idempotency_key=? LIMIT 1');$dup->execute([$idem]);$old=$dup->fetch(PDO::FETCH_ASSOC);if($old){$this->pdo->rollBack();return$old;}$bal=$this->pdo->prepare('SELECT Balance FROM user WHERE id=? FOR UPDATE');$bal->execute([$this->ctx['id']]);if((int)$bal->fetchColumn()<$amount)throw new RuntimeException('موجودی کافی نیست.');$this->pdo->prepare('UPDATE user SET Balance=Balance-? WHERE id=?')->execute([$amount,$this->ctx['id']]);$this->pdo->prepare("INSERT INTO reseller_settlements(request_id,reseller_id,payout_account_id,amount,fee,net_amount,status,idempotency_key,requested_at) VALUES(?,?,?,?,?,?,'pending',?,?)")->execute([$id,$this->ctx['id'],$acc['id'],$amount,$fee,$net,$idem,time()]);$this->pdo->prepare('INSERT INTO reseller_wallet_ledger(from_user_id,to_user_id,amount,reason,actor_reseller_id,created_at) VALUES(?,?,?,?,?,?)')->execute([$this->ctx['id'],'settlement_escrow',$amount,'settlement_reserve',$this->ctx['id'],time()]);$this->pdo->commit();rxp_audit($this->pdo,$this->ctx,'settlement.request',$id,['amount'=>$amount,'net'=>$net]);return['request_id'=>$id,'amount'=>$amount,'fee'=>$fee,'net_amount'=>$net,'status'=>'pending'];}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function validIban(string$iban):bool{if(!preg_match('/^IR\d{24}$/',$iban))return false;$rearr=substr($iban,4).substr($iban,0,4);$num='';foreach(str_split($rearr)as$c)$num.=ctype_alpha($c)?(string)(ord($c)-55):$c;$mod=0;foreach(str_split($num)as$d)$mod=($mod*10+(int)$d)%97;return$mod===1;}
 public function cancel(string$id):void{$this->pdo->beginTransaction();try{$q=$this->pdo->prepare("SELECT * FROM reseller_settlements WHERE request_id=? AND reseller_id=? FOR UPDATE");$q->execute([$id,$this->ctx['id']]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r||$r['status']!=='pending')throw new RuntimeException('درخواست قابل لغو نیست.');$this->pdo->prepare("UPDATE reseller_settlements SET status='cancelled',reviewed_at=? WHERE request_id=? AND status='pending'")->execute([time(),$id]);$this->pdo->prepare('UPDATE user SET Balance=Balance+? WHERE id=?')->execute([(int)$r['amount'],$this->ctx['id']]);$this->pdo->prepare('INSERT INTO reseller_wallet_ledger(from_user_id,to_user_id,amount,reason,actor_reseller_id,created_at) VALUES(?,?,?,?,?,?)')->execute(['settlement_escrow',$this->ctx['id'],(int)$r['amount'],'settlement_cancel_refund',$this->ctx['id'],time()]);$this->pdo->commit();rxp_audit($this->pdo,$this->ctx,'settlement.cancel',$id);}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
}
