<?php
declare(strict_types=1);
final class ResellerMessaging {
 private PDO $pdo; private array $ctx;
 public function __construct(PDO $pdo,array $ctx){$this->pdo=$pdo;$this->ctx=$ctx;}
 public function enqueueBroadcast(string $title,string $message): array { $this->validate($message);$since=strtotime('today');$q=$this->pdo->prepare("SELECT COUNT(*) FROM reseller_broadcasts WHERE actor_reseller_id=? AND kind='broadcast' AND created_at>=?");$q->execute([$this->ctx['id'],$since]);if((int)$q->fetchColumn()>=3)throw new RuntimeException('حداکثر سه پیام همگانی در روز مجاز است.');[$scope,$params]=rxp_customer_scope($this->ctx,'u');$q=$this->pdo->prepare("SELECT u.id,u.bottype FROM user u WHERE $scope ORDER BY u.id LIMIT 5000");$q->execute($params);return $this->create('broadcast',$title,$message,$q->fetchAll(PDO::FETCH_ASSOC)); }
 public function enqueueDirect(string $userId,string $message): array { $this->validate($message);$u=rxp_assert_customer($this->pdo,$this->ctx,$userId);$since=strtotime('today');$q=$this->pdo->prepare("SELECT COUNT(*) FROM reseller_broadcasts WHERE actor_reseller_id=? AND kind='direct' AND created_at>=?");$q->execute([$this->ctx['id'],$since]);if((int)$q->fetchColumn()>=100)throw new RuntimeException('سقف پیام مستقیم روزانه تکمیل شده است.');return $this->create('direct','پیام مستقیم',$message,[['id'=>$u['id'],'bottype'=>$u['bottype']??'']]); }
 public function cancel(string $id): bool {$this->pdo->beginTransaction();try{$q=$this->pdo->prepare("UPDATE reseller_broadcasts SET status='cancelled',completed_at=? WHERE broadcast_id=? AND actor_reseller_id=? AND status IN ('queued','processing')");$q->execute([time(),$id,$this->ctx['id']]);if($q->rowCount()!==1){$this->pdo->rollBack();return false;}$this->pdo->prepare("UPDATE reseller_message_queue SET status='cancelled',claim_token=NULL WHERE broadcast_id=? AND status IN ('queued','retry')")->execute([$id]);$this->pdo->commit();return true;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function create(string $kind,string $title,string $message,array $users): array {if(!$users)throw new RuntimeException('مخاطبی در محدوده شما یافت نشد.');$tokenOwner=[];if($this->ctx['scope_ids']){[$ph,$ids]=rxp_in($this->ctx['scope_ids']);$q=$this->pdo->prepare("SELECT id_user,bot_token FROM botsaz WHERE id_user IN ($ph)");$q->execute($ids);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$b)$tokenOwner[(string)$b['bot_token']]=(string)$b['id_user'];}$id=bin2hex(random_bytes(16));$now=time();$this->pdo->beginTransaction();try{$this->pdo->prepare('INSERT INTO reseller_broadcasts(broadcast_id,actor_reseller_id,title,message,kind,status,total_count,created_at) VALUES(?,?,?,?,?,\'queued\',?,?)')->execute([$id,$this->ctx['id'],mb_substr($title,0,191),$message,$kind,count($users),$now]);$ins=$this->pdo->prepare('INSERT IGNORE INTO reseller_message_queue(broadcast_id,recipient_user_id,bot_owner_id,status,next_attempt_at) VALUES(?,?,?,\'queued\',0)');foreach($users as$u){$bt=(string)($u['bottype']??'');$owner=$tokenOwner[$bt]??null;$ins->execute([$id,(string)$u['id'],$owner]);}$actual=$this->pdo->prepare('SELECT COUNT(*) FROM reseller_message_queue WHERE broadcast_id=?');$actual->execute([$id]);$count=(int)$actual->fetchColumn();$this->pdo->prepare('UPDATE reseller_broadcasts SET total_count=? WHERE broadcast_id=?')->execute([$count,$id]);$this->pdo->commit();return['broadcast_id'=>$id,'count'=>$count];}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function validate(string$message):void{$message=trim($message);if($message===''||mb_strlen($message)>3500)throw new RuntimeException('متن باید بین ۱ تا ۳۵۰۰ کاراکتر باشد.');}
}
