<?php
declare(strict_types=1);
final class RedFoxTicketAttachments {
 private const MAX=8388608;
 private const ALLOWED=['image/jpeg'=>['jpg','photo'],'image/png'=>['png','photo'],'image/webp'=>['webp','photo'],'video/mp4'=>['mp4','video'],'application/pdf'=>['pdf','document'],'text/plain'=>['txt','document']];
 public static function store(array$file,string$root):array{if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file((string)$file['tmp_name']))throw new RuntimeException('آپلود معتبر نیست.');$size=(int)($file['size']??0);if($size<1||$size>self::MAX)throw new RuntimeException('حداکثر حجم پیوست ۸ مگابایت است.');$fi=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$fi->file((string)$file['tmp_name']);if(!isset(self::ALLOWED[$mime]))throw new RuntimeException('نوع فایل مجاز نیست.');[$ext,$kind]=self::ALLOWED[$mime];$dir=$root.'/storage/tickets/'.date('Y/m');if(!is_dir($dir)&&!mkdir($dir,0750,true))throw new RuntimeException('ساخت مسیر پیوست ناموفق بود.');$name=bin2hex(random_bytes(20)).'.'.$ext;$path=$dir.'/'.$name;if(!move_uploaded_file((string)$file['tmp_name'],$path))throw new RuntimeException('ذخیره پیوست ناموفق بود.');chmod($path,0640);$original=mb_substr(preg_replace('/[^\pL\pN._ -]/u','_',basename((string)($file['name']??'file'))),0,180);return['storage_name'=>substr($path,strlen($root)+1),'original_name'=>$original,'mime'=>$mime,'size'=>$size,'sha256'=>hash_file('sha256',$path),'kind'=>$kind,'path'=>$path];}
 public static function send(string$chatId,array$a,string$caption,?string$token=null):array{$input=new CURLFile($a['path'],$a['mime'],$a['original_name']);$method=$a['kind']==='photo'?'sendPhoto':($a['kind']==='video'?'sendVideo':'sendDocument');$field=$a['kind']==='photo'?'photo':($a['kind']==='video'?'video':'document');$payload=['chat_id'=>$chatId,$field=>$input,'caption'=>$caption];return telegram($method,$payload,$token);}
 public static function absolute(string$root,string$relative):string{$base=realpath($root.'/storage/tickets');$path=realpath($root.'/'.$relative);if(!$base||!$path||strpos($path,$base.DIRECTORY_SEPARATOR)!==0||!is_file($path))throw new RuntimeException('فایل پیوست یافت نشد.');return$path;}
}
