<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/lib/Portal.php'; require_once __DIR__.'/lib/Layout.php';
$ctx=rxp_context($pdo);rxp_require_perm($ctx,'reports');[$scope,$params]=rxp_invoice_scope($ctx,'i');
$status=trim((string)($_GET['status']??''));$search=trim((string)($_GET['q']??''));$where=$scope;$pp=$params;if($status!==''){$where.=' AND i.Status=?';$pp[]=$status;}if($search!==''){$where.=' AND (i.id_invoice LIKE ? OR i.id_user LIKE ? OR i.username LIKE ? OR i.name_product LIKE ?)';$l='%'.$search.'%';$pp=array_merge($pp,[$l,$l,$l,$l]);}
if(($_GET['export']??'')==='csv'){
 header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="reseller-invoices.csv"');$o=fopen('php://output','w');fprintf($o,"\xEF\xBB\xBF");fputcsv($o,['id','user','config','product','price','volume','days','status','time']);$q=$pdo->prepare("SELECT * FROM invoice i WHERE $where ORDER BY CAST(i.time_sell AS UNSIGNED) DESC LIMIT 10000");$q->execute($pp);while($r=$q->fetch(PDO::FETCH_ASSOC))fputcsv($o,[$r['id_invoice'],$r['id_user'],$r['username'],$r['name_product'],$r['price_product'],$r['Volume'],$r['Service_time'],$r['Status'],$r['time_sell']]);fclose($o);exit;
}
$page=max(1,(int)($_GET['p']??1));$per=50;$off=($page-1)*$per;$q=$pdo->prepare("SELECT COUNT(*) FROM invoice i WHERE $where");$q->execute($pp);$total=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT i.* FROM invoice i WHERE $where ORDER BY CAST(i.time_sell AS UNSIGNED) DESC LIMIT $per OFFSET $off");$q->execute($pp);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
rxp_layout_start($ctx,'سفارش‌ها','invoices.php');?>
<div><h1 class="rxp-title">سفارش‌ها</h1><div class="rxp-sub"><?=$total?> سفارش در محدوده نمایندگی</div></div><div class="rxp-card"><form method="get" class="rxp-form"><div class="rxp-field"><label>جستجو</label><input name="q" value="<?=rxp_h($search)?>"></div><div class="rxp-field"><label>وضعیت</label><select name="status"><option value="">همه</option><?php foreach(['active','unpaid','Unpaid','end_of_time','end_of_volume','disabled','send_on_hold'] as $s):?><option <?=$status===$s?'selected':''?>><?=rxp_h($s)?></option><?php endforeach;?></select></div><button class="rxp-btn">فیلتر</button><a class="rxp-btn green" href="?<?=rxp_h(http_build_query(['q'=>$search,'status'=>$status,'export'=>'csv']))?>">CSV</a></form></div>
<div class="rxp-card"><div class="rxp-table-wrap"><table class="rxp-table"><thead><tr><th>کد</th><th>مشتری</th><th>محصول</th><th>کانفیگ</th><th>قیمت</th><th>حجم/روز</th><th>وضعیت</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><a href="services.php?id=<?=urlencode((string)$r['id_invoice'])?>"><code><?=rxp_h($r['id_invoice'])?></code></a></td><td><a href="users.php?id=<?=urlencode((string)$r['id_user'])?>"><?=rxp_h($r['id_user'])?></a></td><td><?=rxp_h($r['name_product'])?></td><td style="direction:ltr"><?=rxp_h($r['username'])?></td><td><?=rxp_money($r['price_product'])?></td><td><?=rxp_h($r['Volume'])?> / <?=rxp_h($r['Service_time'])?></td><td><span class="rxp-badge"><?=rxp_h($r['Status'])?></span></td></tr><?php endforeach;?></tbody></table></div><?php rxp_pager($page,(int)ceil($total/$per),['q'=>$search,'status'=>$status]);?></div><?php rxp_layout_end();
