<?php
require_once __DIR__.'/../config.php';require_once __DIR__.'/lib/Portal.php';require_once __DIR__.'/lib/Layout.php';
$ctx=rxp_context($pdo);rxp_require_perm($ctx,'products');$owner=rxp_target_reseller($ctx);$botDir=rxp_bot_dir($pdo,$owner);$flash='';$ft='ok';$q=$pdo->prepare('SELECT agent FROM user WHERE id=? LIMIT 1');$q->execute([$owner]);$agentType=(string)$q->fetchColumn();
$priceFile=$botDir?$botDir.'/product.json':'';$nameFile=$botDir?$botDir.'/product_name.json':'';$prices=($priceFile&&is_file($priceFile))?(json_decode((string)file_get_contents($priceFile),true)?:[]):[];$names=($nameFile&&is_file($nameFile))?(json_decode((string)file_get_contents($nameFile),true)?:[]):[];
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 if(!$botDir)rxp_abort(409,'این نماینده ربات اختصاصی ندارد.');$act=(string)($_POST['action']??'');
 try{
  if($act==='create'){$name=mb_substr(trim((string)($_POST['name']??'')),0,191);$price=(int)($_POST['price']??0);$vol=max(0,(int)($_POST['volume']??0));$days=max(0,(int)($_POST['days']??0));$catId=max(0,(int)($_POST['category']??0));if($name===''||$price<1||$price>1000000000||$vol>100000||$days>36500)throw new DomainException('مشخصات محصول خارج از محدوده مجاز است.');if($catId>0){$c=$pdo->prepare("SELECT COUNT(*) FROM reseller_categories WHERE id=? AND reseller_id=? AND status='active'");$c->execute([$catId,$owner]);if((int)$c->fetchColumn()!==1)throw new DomainException('دسته‌بندی مستقل نامعتبر است.');}$code='rp_'.$owner.'_'.bin2hex(random_bytes(4));$pdo->beginTransaction();$q=$pdo->prepare("INSERT INTO product(code_product,name_product,price_product,Volume_constraint,Location,Service_time,agent,note,data_limit_reset,one_buy_status,inbounds,proxies,category,hide_panel) VALUES(?,?,?,?,'/all',?,?,?,'no_reset','0',NULL,NULL,'','{}')");$q->execute([$code,$name,(string)$price,(string)$vol,(string)$days,$owner,'reseller_owned:'.$owner]);if($catId>0)$pdo->prepare('INSERT INTO reseller_product_categories(reseller_id,product_code,category_id,created_at) VALUES(?,?,?,?)')->execute([$owner,$code,$catId,time()]);$pdo->commit();rxp_audit($pdo,$ctx,'product.create',$code,['owner'=>$owner,'category_id'=>$catId]);$flash='محصول اختصاصی ساخته شد.';}
  elseif($act==='delete'){$code=trim((string)($_POST['code']??''));$pdo->beginTransaction();$pdo->prepare('DELETE FROM reseller_product_categories WHERE reseller_id=? AND product_code=?')->execute([$owner,$code]);$q=$pdo->prepare("DELETE FROM product WHERE code_product=? AND agent=? AND note=?");$q->execute([$code,$owner,'reseller_owned:'.$owner]);if($q->rowCount()!==1)throw new DomainException('محصول اختصاصی مجاز برای حذف نیست.');$pdo->commit();unset($prices[$code],$names[$code]);file_put_contents($priceFile,json_encode($prices,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);file_put_contents($nameFile,json_encode($names,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);rxp_audit($pdo,$ctx,'product.delete',$code,['owner'=>$owner]);$flash='محصول اختصاصی حذف شد.';}
  else{$code=trim((string)($_POST['code']??''));$q=$pdo->prepare("SELECT * FROM product WHERE code_product=? AND (agent=? OR agent=? OR agent='all') LIMIT 1");$q->execute([$code,$agentType,$owner]);$base=$q->fetch(PDO::FETCH_ASSOC);if(!$base)throw new DomainException('محصول مجاز نیست.');if($act==='save'){$price=(int)($_POST['price']??0);$name=trim((string)($_POST['name']??''));if($price<(int)$base['price_product'])throw new DomainException('قیمت نمی‌تواند از قیمت پایه کمتر باشد.');$prices[$code]=$price;$names[$code]=mb_substr($name?:$base['name_product'],0,191);file_put_contents($priceFile,json_encode($prices,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);file_put_contents($nameFile,json_encode($names,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);rxp_audit($pdo,$ctx,'product.override',$code,['owner'=>$owner,'price'=>$price]);$flash='قیمت و نام نمایشی ذخیره شد.';}elseif($act==='reset'){unset($prices[$code],$names[$code]);file_put_contents($priceFile,json_encode($prices,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);file_put_contents($nameFile,json_encode($names,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);rxp_audit($pdo,$ctx,'product.reset',$code,['owner'=>$owner]);$flash='به مقدار پایه بازگردانده شد.';}}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$flash=rxp_public_exception_message($e, basename(__FILE__));$ft='err';}
}
$catsStmt=$pdo->prepare("SELECT id,name FROM reseller_categories WHERE reseller_id=? AND status='active' ORDER BY sort_order,id");$catsStmt->execute([$owner]);$cats=$catsStmt->fetchAll(PDO::FETCH_ASSOC);$q=$pdo->prepare("SELECT code_product,name_product,price_product,Volume_constraint,Service_time,category,Location,agent,note FROM product WHERE agent=? OR agent=? OR agent='all' ORDER BY (agent=? ) DESC,CAST(price_product AS UNSIGNED)");$q->execute([$agentType,$owner,$owner]);$products=$q->fetchAll(PDO::FETCH_ASSOC);rxp_layout_start($ctx,'محصولات','products.php');rxp_flash($flash,$ft);?>
<h1 class="rxp-title">محصولات و قیمت اختصاصی</h1><?php if($ctx['role']==='super'):?><div class="rxp-card"><form method="get" class="rxp-form"><div class="rxp-field"><label>مدیریت برای</label><select name="owner" onchange="this.form.submit()"><?php foreach($ctx['scope_ids'] as $id):?><option value="<?=rxp_h($id)?>" <?=$owner===$id?'selected':''?>>نماینده #<?=rxp_h($id)?></option><?php endforeach;?></select></div></form></div><?php endif;?>
<?php if(!$botDir):?><div class="rxp-flash err">این نماینده ربات اختصاصی ندارد.</div><?php else:?><div class="rxp-card"><h2>ساخت محصول اختصاصی</h2><form method="post" class="rxp-form"><input type="hidden" name="owner" value="<?=rxp_h($owner)?>"><input type="hidden" name="action" value="create"><div class="rxp-field"><label>نام</label><input name="name" required></div><div class="rxp-field"><label>قیمت</label><input type="number" name="price" min="1" required></div><div class="rxp-field"><label>حجم GB؛ صفر نامحدود</label><input type="number" name="volume" min="0"></div><div class="rxp-field"><label>روز؛ صفر نامحدود</label><input type="number" name="days" min="0"></div><div class="rxp-field"><label>دسته مستقل</label><select name="category"><option value="0">بدون دسته</option><?php foreach($cats as $c):?><option value="<?=(int)$c['id']?>"><?=rxp_h($c['name'])?></option><?php endforeach;?></select></div><button class="rxp-btn green">ساخت</button></form></div><?php endif;?>
<div class="rxp-card"><p class="rxp-muted">محصول اختصاصی فقط در ربات همان نماینده نمایش داده می‌شود. محصولات پایه قابل حذف نیستند و قیمت override آن‌ها از قیمت پایه کمتر نمی‌شود.</p><div class="rxp-table-wrap"><table class="rxp-table"><tr><th>کد</th><th>نام</th><th>حجم/روز</th><th>قیمت پایه</th><th>نوع</th><th>تنظیم</th></tr><?php foreach($products as $p):$c=(string)$p['code_product'];$custom=(string)$p['agent']===$owner;?><tr><td><code><?=rxp_h($c)?></code></td><td><?=rxp_h($p['name_product'])?></td><td><?=rxp_h($p['Volume_constraint'])?> / <?=rxp_h($p['Service_time'])?></td><td><?=rxp_money($p['price_product'])?></td><td><span class="rxp-badge"><?=$custom?'اختصاصی':'پایه'?></span></td><td><form method="post" class="rxp-form"><input type="hidden" name="owner" value="<?=rxp_h($owner)?>"><input type="hidden" name="action" value="save"><input type="hidden" name="code" value="<?=rxp_h($c)?>"><input name="name" value="<?=rxp_h($names[$c]??$p['name_product'])?>" style="width:140px"><input type="number" name="price" min="<?=(int)$p['price_product']?>" value="<?=(int)($prices[$c]??$p['price_product'])?>" style="width:100px"><button class="rxp-btn">ذخیره</button></form><?php if($custom):?><form method="post" onsubmit="return confirm('محصول اختصاصی حذف شود؟')"><input type="hidden" name="owner" value="<?=rxp_h($owner)?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="code" value="<?=rxp_h($c)?>"><button class="rxp-btn red">حذف</button></form><?php else:?><form method="post"><input type="hidden" name="owner" value="<?=rxp_h($owner)?>"><input type="hidden" name="action" value="reset"><input type="hidden" name="code" value="<?=rxp_h($c)?>"><button class="rxp-btn gray">پایه</button></form><?php endif;?></td></tr><?php endforeach;?></table></div></div><?php rxp_layout_end();
