<?php
require_once __DIR__.'/../config.php';
require_once __DIR__.'/../botapi.php';
require_once __DIR__.'/../function.php';
require_once __DIR__.'/../panels.php';
require_once __DIR__.'/../lib/ResellerServiceOperations.php';
require_once __DIR__.'/lib/Portal.php';
require_once __DIR__.'/lib/Layout.php';
$ctx=rxp_context($pdo);rxp_require_perm($ctx,'reports');$id=trim((string)($_GET['id']??$_POST['invoice_id']??''));
if($id===''){header('Location: invoices.php');exit;}$inv=rxp_assert_invoice($pdo,$ctx,$id);$flash='';$ft='ok';$ops=new ResellerServiceOperations($pdo,$ctx);
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 try{rxp_require_perm($ctx,'extend_user');$action=(string)($_POST['service_action']??'');$amount=(int)($_POST['amount']??0);$product=(string)($_POST['product_code']??'');$idem=(string)($_POST['idempotency_key']??'');$result=$ops->execute($inv,$action,$amount,$product,$idem);if(!empty($result['ok'])){$flash='عملیات با موفقیت انجام شد. مبلغ: '.number_format((int)$result['price']).' تومان';rxp_audit($pdo,$ctx,'service.'.$action,$id,['operation_id'=>$result['operation_id']??'','price'=>$result['price']??0]);$inv=rxp_assert_invoice($pdo,$ctx,$id);}else{$flash='عملیات ناموفق بود و در صورت کسر، مبلغ برگشت داده شد. '.$result['error'];$ft='err';}}
 catch(Throwable $e){$flash=rxp_public_exception_message($e, basename(__FILE__));$ft='err';}
}
$info=(string)($inv['user_info']??'');$decoded=json_decode($info,true);$sub='';$configs=[];if(is_array($decoded)){$sub=(string)($decoded['subscription_url']??$decoded['sub_url']??'');$configs=is_array($decoded['links']??null)?$decoded['links']:[];}elseif(preg_match('#^https?://#',$info))$sub=$info;
$renewProducts=[];if(rxp_can($ctx,'extend_user')){try{$owner=(string)($inv['refral']??'');if(!in_array($owner,$ctx['scope_ids'],true)){$owner=$ctx['id'];if(!empty($inv['bottype'])){$ob=$pdo->prepare('SELECT id_user FROM botsaz WHERE bot_token=? LIMIT 1');$ob->execute([(string)$inv['bottype']]);$candidate=(string)$ob->fetchColumn();if(in_array($candidate,$ctx['scope_ids'],true))$owner=$candidate;}}$q=$pdo->prepare('SELECT agent FROM user WHERE id=?');$q->execute([$owner]);$ag=(string)$q->fetchColumn();$q=$pdo->prepare("SELECT code_product,name_product,price_product,Volume_constraint,Service_time FROM product WHERE agent=? OR agent=? OR agent='all' ORDER BY CAST(price_product AS UNSIGNED)");$q->execute([$ag,$owner]);$renewProducts=$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}}
$idem=bin2hex(random_bytes(16));
rxp_layout_start($ctx,'جزئیات سرویس','services.php');rxp_flash($flash,$ft);?>
<div><h1 class="rxp-title">سرویس <?=rxp_h($id)?></h1><div class="rxp-sub">عملیات مالی و پنل با Idempotency و جبران خودکار خطا اجرا می‌شود.</div></div>
<div class="rxp-grid"><div class="rxp-stat"><b><?=rxp_h($inv['Status'])?></b><span>وضعیت</span></div><div class="rxp-stat"><b><?=rxp_h($inv['Volume'])?> GB</b><span>حجم</span></div><div class="rxp-stat"><b><?=rxp_h($inv['Service_time'])?> روز</b><span>مدت</span></div><div class="rxp-stat"><b><?=rxp_money($inv['price_product'])?></b><span>قیمت</span></div></div>
<div class="rxp-card"><h2>اطلاعات سرویس</h2><div class="rxp-table-wrap"><table class="rxp-table"><tr><th>مشتری</th><td><a href="users.php?id=<?=urlencode((string)$inv['id_user'])?>"><?=rxp_h($inv['id_user'])?></a></td></tr><tr><th>محصول</th><td><?=rxp_h($inv['name_product'])?></td></tr><tr><th>نام کانفیگ</th><td style="direction:ltr"><?=rxp_h($inv['username'])?></td></tr><tr><th>پنل/لوکیشن</th><td><?=rxp_h($inv['Service_location'])?></td></tr><tr><th>یادداشت</th><td><?=rxp_h($inv['note'])?></td></tr></table></div></div>
<?php if(rxp_can($ctx,'extend_user')):?><div class="rxp-card"><h2>عملیات سرویس با کسر از کیف پول نماینده مالک</h2><div class="rxp-form">
<form method="post" class="rxp-form" onsubmit="return confirm('افزایش حجم و کسر هزینه انجام شود؟')"><input type="hidden" name="invoice_id" value="<?=rxp_h($id)?>"><input type="hidden" name="service_action" value="extra_volume"><input type="hidden" name="idempotency_key" value="<?=$idem?>"><div class="rxp-field"><label>حجم اضافه (GB)</label><input type="number" name="amount" min="1" max="10000" required></div><button class="rxp-btn">افزایش حجم</button></form>
<form method="post" class="rxp-form" onsubmit="return confirm('افزایش زمان و کسر هزینه انجام شود؟')"><input type="hidden" name="invoice_id" value="<?=rxp_h($id)?>"><input type="hidden" name="service_action" value="extra_time"><input type="hidden" name="idempotency_key" value="<?=bin2hex(random_bytes(16))?>"><div class="rxp-field"><label>زمان اضافه (روز)</label><input type="number" name="amount" min="1" max="10000" required></div><button class="rxp-btn">افزایش زمان</button></form></div>
<?php if($renewProducts):?><form method="post" class="rxp-form" style="margin-top:14px" onsubmit="return confirm('تمدید و کسر هزینه انجام شود؟')"><input type="hidden" name="invoice_id" value="<?=rxp_h($id)?>"><input type="hidden" name="service_action" value="renew"><input type="hidden" name="idempotency_key" value="<?=bin2hex(random_bytes(16))?>"><div class="rxp-field"><label>محصول تمدید</label><select name="product_code" required><?php foreach($renewProducts as $p):?><option value="<?=rxp_h($p['code_product'])?>"><?=rxp_h($p['name_product'])?> — <?=rxp_h($p['Volume_constraint'])?>GB / <?=rxp_h($p['Service_time'])?> روز — <?=rxp_money($p['price_product'])?></option><?php endforeach;?></select></div><button class="rxp-btn green">تمدید سرویس</button></form><?php endif;?><p class="rxp-muted">اگر API پنل قبل از اعمال تغییر خطا بدهد، مبلغ رزروشده خودکار برگردانده می‌شود. وضعیت‌های نامطمئن در صف «نیازمند تطبیق» قرار می‌گیرند و دوباره خودکار اجرا نمی‌شوند.</p></div><?php endif;?>
<?php if($sub!==''):?><div class="rxp-card"><h2>لینک اشتراک</h2><textarea readonly style="width:100%;min-height:70px;direction:ltr;background:var(--surface-2);color:var(--text-main);border:1px solid var(--border-mid);border-radius:8px;padding:10px"><?=rxp_h($sub)?></textarea></div><?php endif;?>
<?php if($configs):?><div class="rxp-card"><h2>کانفیگ‌ها</h2><?php foreach($configs as $c):?><textarea readonly style="width:100%;min-height:55px;direction:ltr;margin:5px 0;background:var(--surface-2);color:var(--text-main);border:1px solid var(--border-mid);border-radius:8px;padding:10px"><?=rxp_h($c)?></textarea><?php endforeach;?></div><?php endif;?>
<?php rxp_layout_end();
