<?php
declare(strict_types=1);
require_once __DIR__.'/../config.php';require_once __DIR__.'/lib/Portal.php';require_once __DIR__.'/lib/Layout.php';
$ctx=rxp_context($pdo);rxp_require_perm($ctx,'profile');$flash='';$ft='ok';
try{rx_require_schema($pdo,['reseller_deposit_requests']);}catch(Throwable$e){rxp_abort(503,'ساختار واریز نماینده هنوز بروزرسانی نشده است؛ ادمین باید Migrationها را اجرا کند.');}
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 try{$act=(string)($_POST['action']??'');if($act==='request'){$amount=(int)($_POST['amount']??0);$reference=mb_substr(trim((string)($_POST['reference']??'')),0,191);$note=mb_substr(trim((string)($_POST['note']??'')),0,1000);if($amount<10000)throw new DomainException('مبلغ واریز باید حداقل ۱۰٬۰۰۰ تومان باشد.');if($reference===''||mb_strlen($reference)<3)throw new DomainException('شماره پیگیری یا توضیح پرداخت لازم است.');$id=bin2hex(random_bytes(16));$q=$pdo->prepare("INSERT INTO reseller_deposit_requests(request_id,reseller_id,amount,payment_reference,note,status,created_at) VALUES(?,?,?,?,?,'pending',?)");$q->execute([$id,$ctx['id'],$amount,$reference,$note,time()]);rxp_audit($pdo,$ctx,'deposit.request',$id,['amount'=>$amount]);$flash='درخواست واریز ثبت شد؛ پس از بررسی ادمین، اعتبار شما افزایش می‌یابد.';}elseif($act==='cancel'){$id=(string)($_POST['request_id']??'');$q=$pdo->prepare("UPDATE reseller_deposit_requests SET status='cancelled',reviewed_at=? WHERE request_id=? AND reseller_id=? AND status='pending'");$q->execute([time(),$id,$ctx['id']]);if($q->rowCount()!==1)throw new DomainException('درخواست قابل لغو نیست.');$flash='درخواست لغو شد.';}}catch(Throwable$e){$flash=rxp_public_exception_message($e, basename(__FILE__));$ft='err';}}
$cards=[];try{$cards=$pdo->query('SELECT cardnumber,namecard FROM card_number ORDER BY cardnumber')->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable$e){}
$q=$pdo->prepare('SELECT * FROM reseller_deposit_requests WHERE reseller_id=? ORDER BY created_at DESC LIMIT 200');$q->execute([$ctx['id']]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
$labels=['pending'=>'در انتظار بررسی','approved'=>'تأیید و شارژ شد','rejected'=>'رد شده','cancelled'=>'لغوشده'];
rxp_layout_start($ctx,'واریز و تسویه با ادمین','settlements.php');?>
<h1 class="rxp-title">واریز نماینده به ادمین</h1><div class="rxp-sub">در این بخش شماره شبای نماینده لازم نیست. مبلغ را به یکی از حساب‌های ادمین واریز کنید و شماره پیگیری را ثبت کنید؛ پس از تأیید، اعتبار نمایندگی شما افزایش می‌یابد.</div><?php rxp_flash($flash,$ft);?>
<div class="rxp-grid"><div class="rxp-stat"><b><?=rxp_money($ctx['user']['Balance']??0)?></b><span>اعتبار فعلی نمایندگی</span></div><div class="rxp-stat"><b><?=count(array_filter($rows,fn($r)=>$r['status']==='pending'))?></b><span>درخواست منتظر بررسی</span></div></div>
<div class="rxp-card"><h2>حساب‌های ادمین برای واریز</h2><?php if(!$cards):?><p class="rxp-muted">ادمین هنوز شماره کارت معرفی نکرده است؛ با پشتیبانی تماس بگیرید.</p><?php else:?><div class="rxp-table-wrap"><table class="rxp-table"><tr><th>صاحب حساب</th><th>شماره کارت</th></tr><?php foreach($cards as$c):?><tr><td><?=rxp_h($c['namecard'])?></td><td style="direction:ltr"><code><?=rxp_h($c['cardnumber'])?></code></td></tr><?php endforeach;?></table></div><?php endif;?></div>
<div class="rxp-card"><h2>ثبت واریز جدید</h2><form method="post" class="rxp-form"><input type="hidden" name="action" value="request"><div class="rxp-field"><label>مبلغ واریز (تومان)</label><input type="number" name="amount" min="10000" required></div><div class="rxp-field"><label>شماره پیگیری بانکی</label><input name="reference" required></div><div class="rxp-field"><label>توضیح اختیاری</label><input name="note"></div><button class="rxp-btn green">ثبت برای بررسی ادمین</button></form></div>
<div class="rxp-card"><h2>تاریخچه واریزها</h2><div class="rxp-table-wrap"><table class="rxp-table"><tr><th>زمان شمسی</th><th>مبلغ</th><th>پیگیری</th><th>وضعیت</th><th>توضیح ادمین</th><th></th></tr><?php foreach($rows as$r):?><tr><td><?=rx_fa_date((int)$r['created_at'])?></td><td><?=rxp_money($r['amount'])?></td><td><?=rxp_h($r['payment_reference'])?></td><td><span class="rxp-badge"><?=rxp_h($labels[$r['status']]??$r['status'])?></span></td><td><?=rxp_h($r['admin_note']??'—')?></td><td><?php if($r['status']==='pending'):?><form method="post"><input type="hidden" name="action" value="cancel"><input type="hidden" name="request_id" value="<?=rxp_h($r['request_id'])?>"><button class="rxp-btn red">لغو</button></form><?php endif;?></td></tr><?php endforeach;?></table></div></div><?php rxp_layout_end();
