<?php
require_once __DIR__.'/../config.php';require_once __DIR__.'/../botapi.php';require_once __DIR__.'/lib/Portal.php';require_once __DIR__.'/lib/Layout.php';$ctx=rxp_context($pdo);rxp_require_perm($ctx,'subresellers');$flash='';$ft='ok';
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){$act=(string)($_POST['action']??'');$cid=trim((string)($_POST['child_id']??''));try{
 if($act==='promote'){ $candidate=rxp_assert_customer($pdo,$ctx,$cid);if(in_array((string)$candidate['agent'],['n','n2'],true))throw new DomainException('این کاربر از قبل نماینده است.');$defaultPerms=[];foreach(['products','categories','reports','set_prices'] as $p)if(rxp_can($ctx,$p))$defaultPerms[$p]=1;$promote=$pdo->prepare("UPDATE user SET agent='n',reseller_role='agent',reseller_parent_id=?,reseller_portal_status='active',reseller_perms=? WHERE id=? AND agent='f'");$promote->execute([$ctx['id'],json_encode($defaultPerms),$cid]);if($promote->rowCount()!==1)throw new DomainException('تبدیل انجام نشد؛ وضعیت کاربر تغییر کرده است.');rxp_audit($pdo,$ctx,'subreseller.promote',$cid);$flash='کاربر به زیرنماینده مستقیم تبدیل شد. رمز پورتال را تنظیم کنید.';}
 else {if(!ctype_digit($cid))throw new DomainException('شناسه نامعتبر');$q=$pdo->prepare("SELECT * FROM user WHERE id=? AND reseller_parent_id=? AND agent IN ('n','n2') LIMIT 1");$q->execute([$cid,$ctx['id']]);$child=$q->fetch(PDO::FETCH_ASSOC);if(!$child)throw new DomainException('این نماینده زیرمجموعه مستقیم شما نیست.');
  if($act==='password'){$pw=(string)($_POST['password']??'');if(mb_strlen($pw)<8)throw new DomainException('رمز حداقل ۸ کاراکتر باشد.');$pdo->prepare('UPDATE user SET panel_password=? WHERE id=?')->execute([password_hash($pw,PASSWORD_DEFAULT),$cid]);rxp_audit($pdo,$ctx,'subreseller.password',$cid);try{sendmessage($cid,"🔐 رمز جدید پنل نمایندگی شما: <code>".htmlspecialchars($pw,ENT_QUOTES)."</code>",null,'HTML');}catch(Throwable $e){}$flash='رمز تنظیم و برای زیرنماینده ارسال شد.';}
  elseif($act==='status'){$st=(string)($_POST['status']??'');if(!in_array($st,['active','disabled'],true))throw new DomainException('وضعیت نامعتبر');$pdo->prepare('UPDATE user SET reseller_portal_status=? WHERE id=? AND reseller_parent_id=?')->execute([$st,$cid,$ctx['id']]);rxp_audit($pdo,$ctx,'subreseller.status',$cid,['status'=>$st]);$flash='وضعیت پورتال تغییر کرد.';}
  elseif($act==='transfer'){$amount=(int)($_POST['amount']??0);if($amount<=0)throw new DomainException('مبلغ نامعتبر');$pdo->beginTransaction();$q=$pdo->prepare('SELECT Balance FROM user WHERE id=? FOR UPDATE');$q->execute([$ctx['id']]);if((int)$q->fetchColumn()<$amount)throw new DomainException('موجودی کافی نیست.');$pdo->prepare('UPDATE user SET Balance=Balance-? WHERE id=?')->execute([$amount,$ctx['id']]);$credit=$pdo->prepare('UPDATE user SET Balance=Balance+? WHERE id=? AND reseller_parent_id=?');$credit->execute([$amount,$cid,$ctx['id']]);if($credit->rowCount()!==1)throw new DomainException('زیرنماینده دیگر در محدوده شما نیست.');$pdo->prepare('INSERT INTO reseller_wallet_ledger(from_user_id,to_user_id,amount,reason,actor_reseller_id,created_at) VALUES(?,?,?,?,?,?)')->execute([$ctx['id'],$cid,$amount,'subreseller_transfer',$ctx['id'],time()]);$pdo->commit();rxp_audit($pdo,$ctx,'subreseller.transfer',$cid,['amount'=>$amount]);$flash='اعتبار منتقل شد.';}
  elseif($act==='permissions'){$allowed=['products','categories','extend_user','charge_user','manage_users','reports','set_prices','broadcast','api','support'];$out=[];foreach($allowed as $p)$out[$p]=(rxp_can($ctx,$p)&&isset($_POST['perm_'.$p]))?1:0;$pdo->prepare('UPDATE user SET reseller_perms=? WHERE id=? AND reseller_parent_id=?')->execute([json_encode($out),$cid,$ctx['id']]);rxp_audit($pdo,$ctx,'subreseller.permissions',$cid,$out);$flash='دسترسی‌ها ذخیره شد.';}
 }
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$flash=rxp_public_exception_message($e, basename(__FILE__));$ft='err';}}
$q=$pdo->prepare("SELECT id,username,namecustom,agent,Balance,reseller_portal_status,reseller_perms FROM user WHERE reseller_parent_id=? AND agent IN ('n','n2') ORDER BY id DESC");$q->execute([$ctx['id']]);$children=$q->fetchAll(PDO::FETCH_ASSOC);rxp_layout_start($ctx,'زیرنمایندگان','subresellers.php');rxp_flash($flash,$ft);?>
<h1 class="rxp-title">زیرنمایندگان مستقیم</h1><div class="rxp-card"><h2>تبدیل یکی از مشتریان خود به زیرنماینده</h2><form method="post" class="rxp-form"><input type="hidden" name="action" value="promote"><div class="rxp-field"><label>آیدی عددی مشتری</label><input name="child_id" required pattern="\d+"></div><button class="rxp-btn">ایجاد زیرنماینده</button></form><p class="rxp-muted">کاربر باید قبلاً از ربات/فروش شما استفاده کرده و در محدوده داده شما باشد.</p></div>
<?php foreach($children as $c):$cp=json_decode((string)$c['reseller_perms'],true)?:[];?><div class="rxp-card"><h2>#<?=rxp_h($c['id'])?> — <?=rxp_h($c['username']?:$c['namecustom'])?> <span class="rxp-badge"><?=rxp_h($c['reseller_portal_status'])?></span></h2><div class="rxp-grid"><div class="rxp-stat"><b><?=rxp_money($c['Balance'])?></b><span>موجودی</span></div><div class="rxp-stat"><b><?=rxp_h($c['agent'])?></b><span>نوع نماینده</span></div></div>
<form method="post" class="rxp-form"><input type="hidden" name="action" value="transfer"><input type="hidden" name="child_id" value="<?=rxp_h($c['id'])?>"><div class="rxp-field"><label>انتقال اعتبار</label><input type="number" name="amount" min="1"></div><button class="rxp-btn green">انتقال</button></form>
<form method="post" class="rxp-form" style="margin-top:8px"><input type="hidden" name="action" value="password"><input type="hidden" name="child_id" value="<?=rxp_h($c['id'])?>"><div class="rxp-field"><label>رمز جدید</label><input type="password" name="password" minlength="8"></div><button class="rxp-btn">تنظیم رمز</button></form>
<form method="post" style="margin-top:12px"><input type="hidden" name="action" value="permissions"><input type="hidden" name="child_id" value="<?=rxp_h($c['id'])?>"><div class="rxp-form"><?php foreach(['products'=>'محصولات','categories'=>'دسته‌بندی','extend_user'=>'تمدید','charge_user'=>'شارژ مشتری','manage_users'=>'مدیریت مشتری','reports'=>'گزارش','set_prices'=>'قیمت‌گذاری','broadcast'=>'پیام‌رسانی','api'=>'API خواندنی','support'=>'تیکت پشتیبانی'] as $p=>$l):if(!rxp_can($ctx,$p))continue;?><label class="rxp-muted"><input type="checkbox" name="perm_<?=$p?>" <?=!empty($cp[$p])?'checked':''?>> <?=$l?></label><?php endforeach;?><button class="rxp-btn gray">ذخیره دسترسی</button></div></form>
<form method="post" style="margin-top:8px"><input type="hidden" name="action" value="status"><input type="hidden" name="child_id" value="<?=rxp_h($c['id'])?>"><input type="hidden" name="status" value="<?=$c['reseller_portal_status']==='disabled'?'active':'disabled'?>"><button class="rxp-btn red"><?=$c['reseller_portal_status']==='disabled'?'فعال‌سازی':'غیرفعال‌سازی پورتال'?></button></form></div><?php endforeach;?><?php if(!$children):?><div class="rxp-card rxp-muted">هنوز زیرنماینده مستقیمی ندارید.</div><?php endif;?><?php rxp_layout_end();
