<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../botapi.php';
require_once __DIR__.'/lib/Portal.php'; require_once __DIR__.'/lib/Layout.php';
$ctx=rxp_context($pdo); rxp_require_perm($ctx,'reports');
$flash='';$flashType='ok';
$uid=trim((string)($_GET['id']??''));
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 $uid=trim((string)($_POST['user_id']??'')); $user=rxp_assert_customer($pdo,$ctx,$uid); $act=(string)($_POST['action']??'');
 try{
  if($act==='status'){rxp_require_perm($ctx,'manage_users');$st=(string)($_POST['status']??'');if(!in_array($st,['Active','Block'],true))throw new DomainException('وضعیت نامعتبر');$pdo->prepare('UPDATE user SET User_Status=? WHERE id=?')->execute([$st,$uid]);rxp_audit($pdo,$ctx,'customer.status',$uid,['status'=>$st]);$flash='وضعیت کاربر تغییر کرد.';}
  elseif($act==='charge'){rxp_require_perm($ctx,'charge_user');$amount=(int)($_POST['amount']??0);if($amount<=0)throw new DomainException('مبلغ باید مثبت باشد.');$pdo->beginTransaction();$q=$pdo->prepare('SELECT Balance FROM user WHERE id=? FOR UPDATE');$q->execute([$ctx['id']]);$bal=(int)$q->fetchColumn();if($bal<$amount)throw new DomainException('موجودی نمایندگی کافی نیست.');$pdo->prepare('UPDATE user SET Balance=Balance-? WHERE id=?')->execute([$amount,$ctx['id']]);$pdo->prepare('UPDATE user SET Balance=Balance+? WHERE id=?')->execute([$amount,$uid]);$pdo->prepare('INSERT INTO reseller_wallet_ledger(from_user_id,to_user_id,amount,reason,actor_reseller_id,created_at) VALUES(?,?,?,?,?,?)')->execute([$ctx['id'],$uid,$amount,'customer_charge',$ctx['id'],time()]);$pdo->commit();rxp_audit($pdo,$ctx,'customer.charge',$uid,['amount'=>$amount]);try{sendmessage($uid,"💰 کیف پول شما توسط نماینده به مبلغ ".number_format($amount)." تومان شارژ شد.",null,'HTML');}catch(Throwable $e){}$flash='انتقال اعتبار انجام شد.';}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$flash=rxp_public_exception_message($e, basename(__FILE__));$flashType='err';}
}
if($uid!==''){
 $user=rxp_assert_customer($pdo,$ctx,$uid);[$invScope,$invParams]=rxp_invoice_scope($ctx,'i');$q=$pdo->prepare("SELECT * FROM invoice i WHERE i.id_user=? AND $invScope ORDER BY CAST(i.time_sell AS UNSIGNED) DESC LIMIT 100");$q->execute(array_merge([$uid],$invParams));$invoices=$q->fetchAll(PDO::FETCH_ASSOC);
 rxp_layout_start($ctx,'پروفایل مشتری','users.php');rxp_flash($flash,$flashType);?>
 <div class="rxp-card"><h2>مشتری #<?=rxp_h($uid)?></h2><div class="rxp-grid"><div class="rxp-stat"><b><?=rxp_h($user['username']??'—')?></b><span>نام کاربری</span></div><div class="rxp-stat"><b><?=rxp_money($user['Balance']??0)?></b><span>موجودی</span></div><div class="rxp-stat"><b><?=rxp_h($user['User_Status']??'—')?></b><span>وضعیت</span></div><div class="rxp-stat"><b><?=count($invoices)?></b><span>سرویس‌ها</span></div></div>
 <?php if(rxp_can($ctx,'charge_user')):?><form method="post" class="rxp-form"><input type="hidden" name="action" value="charge"><input type="hidden" name="user_id" value="<?=rxp_h($uid)?>"><div class="rxp-field"><label>انتقال از کیف پول شما به مشتری</label><input type="number" name="amount" min="1" required></div><button class="rxp-btn green">شارژ مشتری</button></form><?php endif;?>
 <?php if(rxp_can($ctx,'manage_users')):?><form method="post" class="rxp-form" style="margin-top:10px"><input type="hidden" name="action" value="status"><input type="hidden" name="user_id" value="<?=rxp_h($uid)?>"><div class="rxp-field"><label>وضعیت</label><select name="status"><option value="Active">فعال</option><option value="Block">مسدود</option></select></div><button class="rxp-btn">ثبت وضعیت</button></form><?php endif;?></div>
 <div class="rxp-card"><h2>سرویس‌های این مشتری</h2><div class="rxp-table-wrap"><table class="rxp-table"><tr><th>کد</th><th>محصول</th><th>کانفیگ</th><th>حجم</th><th>روز</th><th>وضعیت</th></tr><?php foreach($invoices as $i):?><tr><td><a href="services.php?id=<?=urlencode((string)$i['id_invoice'])?>"><?=rxp_h($i['id_invoice'])?></a></td><td><?=rxp_h($i['name_product'])?></td><td><?=rxp_h($i['username'])?></td><td><?=rxp_h($i['Volume'])?></td><td><?=rxp_h($i['Service_time'])?></td><td><?=rxp_h($i['Status'])?></td></tr><?php endforeach;?></table></div></div>
 <?php rxp_layout_end();exit;
}
[$scope,$params]=rxp_customer_scope($ctx,'u');$search=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['p']??1));$per=50;$off=($page-1)*$per;$where=$scope;$pp=$params;if($search!==''){$where.=' AND (u.id LIKE ? OR u.username LIKE ? OR u.namecustom LIKE ?)';$like='%'.$search.'%';$pp=array_merge($pp,[$like,$like,$like]);}
$q=$pdo->prepare("SELECT COUNT(*) FROM user u WHERE $where");$q->execute($pp);$total=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT u.id,u.username,u.namecustom,u.Balance,u.User_Status,u.register FROM user u WHERE $where ORDER BY CAST(u.register AS UNSIGNED) DESC LIMIT $per OFFSET $off");$q->execute($pp);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
rxp_layout_start($ctx,'مشتریان','users.php');rxp_flash($flash,$flashType);?>
<div><h1 class="rxp-title">مشتریان</h1><div class="rxp-sub"><?=$total?> کاربر در محدوده مجاز شما</div></div><div class="rxp-card"><form class="rxp-form" method="get"><div class="rxp-field"><label>جستجو با آیدی یا نام</label><input name="q" value="<?=rxp_h($search)?>"></div><button class="rxp-btn">جستجو</button></form></div>
<div class="rxp-card"><div class="rxp-table-wrap"><table class="rxp-table"><thead><tr><th>آیدی</th><th>نام</th><th>موجودی</th><th>وضعیت</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><code><?=rxp_h($r['id'])?></code></td><td><?=rxp_h($r['username']?:$r['namecustom'])?></td><td><?=rxp_money($r['Balance'])?></td><td><?=rxp_h($r['User_Status'])?></td><td><a class="rxp-btn gray" href="?id=<?=urlencode((string)$r['id'])?>">مشاهده</a></td></tr><?php endforeach;?></tbody></table></div><?php rxp_pager($page,(int)ceil($total/$per),['q'=>$search]);?></div><?php rxp_layout_end();
